nrf51AdvLogger: UART Driver
UART Driver
Peripheral Drivers
UART Driver for the nrf51822 SoC supports single character printing, stream to printf and a character stream receiver handler.
Files
file uart_nrf.c
This file contains the UART Driver implementation for the nrf51822 SoC.
file uart_nrf.h
This file contains the UART Driver declarations for the nrf51822 SoC.
Macros
#define BUFFER_SIZE 128
Size of the buffer to hold the received characters before LINE_END is received.
#define LINE_END '\n'
The character that is checked by rx_collect to determine if a line of characters is received.
#define UART_BAUDRATE UART_BAUDRATE_BAUDRATE_Baud460800
Baudrate to be used by the UART module.
Functions
void rx_collect (uint8_t rx_data)
Function to add rx_data to a FIFO buffer and calls the receiver handler on LINE_END.
void UART0_IRQHandler (void)
UART interrupt routine.
void uart_putchar (uint8_t cr)
Send a single character through UART This function is used by _write so that printf can be used.
uint32_t _write (int fd, char *str, int len)
Overriding the character stream writer to use UART transmitter.
void set_rx_handler (void(*handler)(uint8_t *ptr))
Function to set the handler to be called by rx_collect when a line is received by UART.
void uart_init (void)
Function to initialize the parameters of UART based on the configurations in board.h.
Variables
uint8_t rx_buffer [BUFFER_SIZE]
Buffer to hold the received characters from UART.
void(* rx_handler)(uint8_t *ptr)
Handler to be called when a line of characters is received from UART.
Detailed Description
UART Driver for the nrf51822 SoC supports single character printing, stream to printf and a character stream receiver handler.
Macro Definition Documentation
#define UART_BAUDRATE UART_BAUDRATE_BAUDRATE_Baud460800
Baudrate to be used by the UART module.
Used by uart_init. In PCA10000 the maximum baudrate is 4,60,800 bps
Definition at line 56 of file uart_nrf.h.
Referenced by uart_init().
Function Documentation
uint32_t _write (int fd, char * str, int len)
Overriding the character stream writer to use UART transmitter.
This is to enable the use of printf defined in stdio.h.
Parameters
fd File descriptor
str Pointer to the character stream to write
len Length of the character stream to write
Returns
The length of the character stream written
Definition at line 101 of file uart_nrf.c.
References uart_putchar().
void rx_collect (uint8_t rx_data)
Function to add rx_data to a FIFO buffer and calls the receiver handler on LINE_END.
Parameters
rx_data Data passed from the receive interrupt routine of UART
Definition at line 55 of file uart_nrf.c.
References BUFFER_SIZE, LINE_END, rx_buffer, and rx_handler.
Referenced by UART0_IRQHandler().
void set_rx_handler (void(*)(uint8_t *ptr) handler)
Function to set the handler to be called by rx_collect when a line is received by UART.
Parameters
handler Pointer to the function to be called when a line is received by UART
Definition at line 108 of file uart_nrf.c.
References rx_handler.
Referenced by obsvr_begin().
void UART0_IRQHandler (void)
UART interrupt routine.
Only data reception causes interrupt. The received data is passed to rx_collect.
Definition at line 75 of file uart_nrf.c.
References rx_collect().
void uart_putchar (uint8_t cr)
Send a single character through UART This function is used by _write so that printf can be used.
Todo:
Add interrupt and WFE to save power
Parameters
cr The character to be sent
Definition at line 85 of file uart_nrf.c.
Referenced by _write().