nrf51AdvLogger: LED Driver
LED Driver
Peripheral Drivers
LED Driver for the PCA1000 board to initialize, switch on, switch off and toggle LEDs.
Files
file leds.h
This file contains the LED Driver for the PCA1000 board.
Functions
static __INLINE void leds_init (void)
Function to initialize the LEDS in the PCA10000 board.
static __INLINE void leds_on (uint32_t led)
Turn a specific LED on.
static __INLINE void leds_off (uint32_t led)
Turn a specific LED of.
static __INLINE void leds_toggle (uint32_t led)
Toggle a specific LED.
Detailed Description
LED Driver for the PCA1000 board to initialize, switch on, switch off and toggle LEDs.
Function Documentation
static __INLINE void leds_off (uint32_t led) static
Turn a specific LED of.
Parameters
led The pin number of the LED to turn off
Definition at line 73 of file leds.h.
References nrf_gpio_pin_set().
Referenced by obsvr_window().
static __INLINE void leds_on (uint32_t led) static
Turn a specific LED on.
Parameters
led The pin number of the LED to turn on
Definition at line 65 of file leds.h.
References nrf_gpio_pin_clear().
Referenced by obsvr_interval().
static __INLINE void leds_toggle (uint32_t led) static
Toggle a specific LED.
Parameters
led The pin number of the LED to toggle
Definition at line 81 of file leds.h.
References nrf_gpio_pin_toggle().