nrf51AdvLogger: Milli-Second RTC Timer
Milli-Second RTC Timer
Peripheral Drivers
Driver to use milli-second timers using RTC1 peripheral.
Files
file clock-nrf.c
This file contains the implementation for milli-second timers using RTC1 peripheral.
file clock-nrf.h
This file contains the declarations for milli-second timers using RTC1 peripheral.
Macros
#define RTC_FREQUENCY 32768
RTC clock freq from LF clock in Hertz.
#define RTC_PRESCALER ((LFCLK_FREQUENCY/RTC_FREQUENCY) - 1)
Prescalar to the LF Clock for the RTC peripheral based on f = LFCLK/(prescaler + 1)
#define RTC_TICKS(ms) ((uint32_t) DIV_ROUNDED((RTC_FREQUENCY*ms) , 1000))
Calculation to findout the number of RTC ticks for the passed time in milli-seconds.
Enumerations
enum timer_num {
MS_TIMER0, MS_TIMER1, MS_TIMER2, MS_TIMER3,
MS_TIMER_MAX
}
Enumeration used for specifying the four timers that can be used with a RTC peripheral.
enum timer_mode { SINGLE_CALL, REPEATED_CALL }
Enumeration to specify the mode of operation of the timer.
Functions
void ms_timer_init (void)
Initialize the RTC1 peripheral to use as a milli-second timer.
void start_ms_timer (timer_num id, timer_mode mode, uint32_t ticks, void(*handler)(void))
Start a milli-second timer.
void stop_ms_timer (timer_num id)
Stop a milli-second timer.
bool is_ms_timer_on (timer_num id)
Returns if a timer is on.
void RTC1_IRQHandler ()
Function for handling the RTC1 interrupts.
Variables
static uint32_t ms_timers_status
Timers currently used based on the first four bits from LSB.
Detailed Description
Driver to use milli-second timers using RTC1 peripheral.
Macro Definition Documentation
#define RTC_FREQUENCY 32768
RTC clock freq from LF clock in Hertz.
Changable, but should be usable by RTC_TICKS
Definition at line 56 of file clock-nrf.h.
Enumeration Type Documentation
enum timer_mode
Enumeration to specify the mode of operation of the timer.
Enumerator
SINGLE_CALL
One shot call of the timer.
REPEATED_CALL
Repeated call of the timer.
Definition at line 82 of file clock-nrf.h.
enum timer_num
Enumeration used for specifying the four timers that can be used with a RTC peripheral.
Enumerator
MS_TIMER0
Millisecond Timer 0.
MS_TIMER1
Millisecond Timer 1.
MS_TIMER2
Millisecond Timer 2.
MS_TIMER3
Millisecond Timer 3.
MS_TIMER_MAX
Not a timer, just used to find the number of timers.
Definition at line 70 of file clock-nrf.h.
Function Documentation
bool is_ms_timer_on (timer_num id)
Returns if a timer is on.
Parameters
id ID of timer being enquired
Returns
Boolean value indicating if a timer is ON
Definition at line 110 of file clock-nrf.c.
References ms_timers_status.
Referenced by obsvr_req().
void ms_timer_init (void)
Initialize the RTC1 peripheral to use as a milli-second timer.
Uses RTC_PRESCALER
Definition at line 55 of file clock-nrf.c.
References MS_TIMER0, MS_TIMER_MAX, ms_timers_status, RTC_PRESCALER, and SINGLE_CALL.
Referenced by main().
void RTC1_IRQHandler ()
Function for handling the RTC1 interrupts.
Triggered Compare register of timer ID
Definition at line 123 of file clock-nrf.c.
References MS_TIMER0, MS_TIMER_MAX, SINGLE_CALL, and stop_ms_timer().
void start_ms_timer (timer_num id, timer_mode mode, uint32_t ticks, void(*)(void) handler)
Start a milli-second timer.
Todo:
Take care of values of ticks passed which are greater than 2^24, now it is suppressed to 2^24 when greater
Warning
Works only for input less than 512000 milli-seconds, or 8.5 min without when RTC_PRESCALER is 0
Parameters
id ID of the timer to be used from timer_num
mode Mode of the timer as specified in timer_mode
ticks The number of ticks of the RTC after which the timer expires
handler Pointer to a function which needs to be called on the expiry of the timer
Note
Starting an already started will restart the timer with the current number of ticks passed. is_ms_timer_on can be used to check if a timer is already running.
Definition at line 72 of file clock-nrf.c.
References lfclk_init(), ms_timers_status, and SINGLE_CALL.
Referenced by obsvr_interval(), and obsvr_req().
void stop_ms_timer (timer_num id)
Stop a milli-second timer.
Parameters
id ID of the timer to be stopped
Note
Stopping an already stopped timer will not be an issue
Definition at line 97 of file clock-nrf.c.
References lfclk_deinit(), ms_timers_status, and SINGLE_CALL.
Referenced by obsvr_req(), and RTC1_IRQHandler().